### ISSUE TITLE
Reg workday api response issue

### ISSUE THREAD

**Issue by sannvarapu** [tonybaloney/workday#6]
Hi 
Thank you very much for the project you have provided for workday. I think I have made a successful call, and do see that the response object is a class. However, I am receiving the following error when I tried to display the data out of response like : print ( resp.data ) statement, generates the following error:

import workday
from workday.auth import WsSecurityCredentialAuthentication
client = workday.WorkdayClient(
wsdls={'dev': 'https://xxyyss.workday.com/ccx/service/dev-tenant/Financial_Management/v33.1'},
authentication=WsSecurityCredentialAuthentication('abc@dev-tenant', 'Welcome123' ),
)

try:
    resp = client.dev.GetAll_Currencies('v33.1')
    print ( "Successful Call")
except Exception as e:
    print ( e )
print ( resp )
print ( type ( resp ))
print ( resp.data )

The output as follows : 

Successful Call
<workday.soap.WorkdayResponse object at 0x0000024EC750A080>
<class 'workday.soap.WorkdayResponse'>
Traceback (most recent call last):
  File "C:/python/python_workday_001.py", line 39, in <module>
    print ( resp.data )
  File "C:\python\lib\site-packages\workday\soap.py", line 113, in data
    return self._response["Response_Data"]
  File "C:\python\lib\site-packages\zeep\xsd\valueobjects.py", line 129, in __getitem__
    return self.__values__[key]
KeyError: 'Response_Data'

I am not sure why it is generating the key error. I dont really understand where I am doing wrong here.  Need your help to fix this issue.

Thanks & Regards
Satish Annavarapu

**Comment by sannvarapu** [comment]
I have downloaded a soap ui tool, and have tested it using the same link, and credentials, it started giving me user id , and password error-invalid.
But how do I display that in the python. I get returned <workday.soap.WorkdayResponse object at 0x000001CB305DDE80> object, but I couldnt display it nor its failing to display it
